### ISSUE TITLE
Question about 

### ISSUE THREAD

**Issue by modzia** [ptasz3k/Kimbus#5]
What's the easiest way to convert the result from ReadHoldingRegisters to decimal?
Example:
decimal a;
a = ReadHoldingRegisters(1,6820,2)

Best
KS

**Comment by ptasz3k** [comment]
Hello,

sorry for the late response. Easiest way would be to simply cast each resulting value do decimal:

```
using (var mbMaster = new MbMaster(new MbTcpTransport("127.0.0.1", 502)))
{
    mbMaster.Open();
    var result = mbMaster.ReadHoldingRegisters(1, 6820, 2);
    if (result.IsSuccess)
    {
        var decimals = result.Success.Cast<decimal>().ToList();
        /* do something with decimals */
    }
    else
    {
        /* check result.Failure */
    }
}
```

Hope that helps!
